apiVersion: v1
kind: Service
metadata:
  name: {{ include "l8e-harbor.fullname" . }}
  labels:
    {{- include "l8e-harbor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "l8e-harbor.selectorLabels" . | nindent 4 }}