# l8e-harbor Configuration
# This file is mounted into the container and used for service configuration

server:
  host: "0.0.0.0"
  port: 8443
  ssl:
    enabled: true
    cert_file: "/app/certs/server.crt"
    key_file: "/app/certs/server.key"

auth:
  adapter: "local"
  local:
    users_file: "/app/shared/users.json"
  jwt:
    private_key_file: "/app/secrets/jwt-private.pem"
    public_key_file: "/app/secrets/jwt-public.pem"
    issuer: "l8e-harbor"
    audience: ["l8e-harbor-api", "l8e-harbor-ui"]
    expires_in: 3600  # 1 hour

secrets:
  provider: "file"
  file:
    secrets_dir: "/app/shared/secrets"

routes:
  store: "file"
  file:
    routes_file: "/app/shared/routes.json"
    watch: true

observability:
  metrics:
    enabled: true
    path: "/metrics"
    port: 9090
  tracing:
    enabled: false
  logging:
    level: "info"
    format: "json"

proxy:
  timeout: 30s
  max_retries: 3
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    timeout: 60s

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST" 
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Requested-With"

# Bootstrap configuration for initial setup
bootstrap:
  enabled: true
  allow_admin_creation: true