version: '3.8'

services:
  l8e-harbor-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - API_BASE_URL=https://localhost:8443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # For development with hot reload
  l8e-harbor-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=https://localhost:8443
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles: ["dev"]